### ISSUE TITLE
Rationale behind rpn loss in build_loss

### ISSUE THREAD

**Issue by Feynman27** [xmyqsh/FPN#14]
In the build_loss function, I see that the labels are filtered for only foreground/background regions before calculating the rpn class loss and that the SmoothL1Loss is normalized by the number of foreground regions. I don't see this in the original Faster-RCNN implementation. @xmyqsh Can you please explain why this is necessary?

**Comment by xmyqsh** [comment]
@Feynman27 
These logics have been implemented in SmoothL1Loss.cpp, you can check it in caffe source code.

**Comment by Feynman27** [comment]
I see. I'm trying to implement FPNs in caffe v1. So, to my understanding, The equivalent RPN loss in caffe would look something like:

```bash
layer {
  name: "rpn_loss_cls"
  type: "SoftmaxWithLoss"
  bottom: "rpn_cls_score_reshape_reshape_concat"
  bottom: "rpn_labels"
  propagate_down: 1
  propagate_down: 0
  top: "rpn_cls_loss"
  loss_weight: 1
  loss_param {
    ignore_label: -1 # ignore areas we don't care about
    normalize: true
  }
}
layer {
  name: "rpn_loss_bbox"
  type: "SmoothL1Loss"
  bottom: "rpn_bbox_pred_reshape_concat"
  bottom: 'rpn_bbox_targets' # (H*W*A,4)
  bottom: 'rpn_bbox_inside_weights'
  bottom: 'rpn_bbox_outside_weights'
  top: "rpn_loss_bbox"
  loss_weight: 1
  smooth_l1_loss_param { sigma: 3.0 }
}
```

**Comment by xmyqsh** [comment]
@Feynman27 
Your prototxt is right.

The original rpn_loss_bbox in [Faster-rcnn](https://github.com/xmyqsh/py-faster-rcnn/blob/master/lib/rpn/anchor_target_layer.py#L184) is normalized on num(fg + bg), and in my implementation, it is normalized on num(fg).
And my implementation of the loss_bbox in Fast-rcnn phase is same as the original one which has no normalization.

It is worthful for comparing these different settings as well as sigma.
