### ISSUE TITLE
Getting -1 for map using VOC07+12 Trainval for validation

### ISSUE THREAD

**Issue by chriszhenghaochen** [xmyqsh/FPN#27]
Hi,
I used your shared ckpt file to test the validation and run with VOC07 + 12 but get all -1 for mAP, (also try 07 but get the same result :( ) @xmyqsh 

I am wondering anyone has any ideas about this error?

![screenshot from 2017-12-15 19-36-17](https://user-images.githubusercontent.com/11765867/34040569-5091de04-e1cf-11e7-9c83-47f40e653931.png)

**Comment by chriszhenghaochen** [comment]
I modify for reading bugs for tensorflow, but I don't think they should be relevant

```
   checkpoint_dir = os.path.dirname(args.model)
    ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
    if ckpt and ckpt.model_checkpoint_path:
        print('FOUND')
        saver.restore(sess, ckpt.model_checkpoint_path)
    else:
        print('NOT FOUND')
    print ('Loading model weights from {:s}').format(args.model)
```

**Comment by chriszhenghaochen** [comment]
Problem solved, it due to my own path issue :p with VOC0712 directory, the result was now produced

**Comment by imyhxy** [comment]
Hello.
Recently I am try to understand FPN, and would you share how can I get voc0712 dataset correctly?
