### ISSUE TITLE
Memory allocation problem

### ISSUE THREAD

**Issue by leighton613** [xmyqsh/FPN#7]
Hi, I encountered **memory allocation problem** during initialization (solving).

`InternalError (see above for traceback): Dst tensor is not initialized.
	 [[Node: fc7_new/weights/Momentum/Initializer/Const = Const[_class=["loc:@fc7_new/weights"], dtype=DT_FLOAT, value=Tensor<type: float shape: [4096,4096] values: [0 0 0]...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]`

and 

`Limit:                  5111519641`
`InUse:                  5111519488`
`MaxInUse:               5111519488`
`NumAllocs:                     148`
`MaxAllocSize:           4991561984`

My setting:
- single GPU, 11.57G GPU memory available
- (same as faster rcnn) 1 image, shorter side 600, batch size 128, rpn batch size 256
- same error if i change to batch size 16, rpn batch size 32

So I assume the model is too large to fit in?

Tensorflow does have the issue that taking up too much memory in initialization. Wonder anyone has encountered or resolved this issue?

Thanks!

**Comment by xmyqsh** [comment]
@leighton613 
Please pull my latest code.
FPN is memory efficient because its feature is diverse and its Fast-RCNN is light.
I just use 5428MiB memory for training, 1 image, shorter side 800, batch size 512, rpn batch size 256

**Comment by leighton613** [comment]
Thanks @xmyqsh , I haven't check your latest update, which must be very efficient.

Just for comparison, my implementation is adapted from faster-rcnn and is pretty similar to your last version.
- faster-rcnn consumes 5000+ MiB
- fpn w/ only p2 consumes 8600+ MiB
- fpn w/ all layers consumes > 12189 MiB and get `ResourceExhaustedError`.

Any suggestions maybe....?

**Comment by xmyqsh** [comment]
@leighton613 
Your Fast-RCNN consumes 5000+ MiB, so your base model should be ResNet50, right?
And your FPN consumes another 8600+ MiB, I think you haven't share base model between Fast-RCNN and FPN. Meanwhile, your RPN‘s head is incredible big, pay attention to FPN's RPN conv's output is 256, not 512 as in faster-rcnn. And I think yours should larger than 512. P2's feature map which is RPN conv's input is 64 times larger than P5 whose feature map size is same as C5's feature map, this makes RPN conv's output sensitive.
Big P2's feature map also make number of anchors increasing large when anchor scale is increasing. The box-regression layer (reg) and box-classification layer (cls)'s ouput should also increase linearly as number of anchors scale increase.


`your RPN's conv size / faster-rcnn's RPN's conv size = 64 * (your RPN conv's output / faster-rcnn's RPN's output)`
`your rgs/cls layer size / faster-rcnn's rgs/cls layer size = (your RPN conv's output / faster-rcnn's RPN's output) * 64 * (your number of anchor's scale / faster-rcnn's RPN's anchor's scale)`
and
`your RPN's conv size / my RPN's conv size = (your RPN conv's output / ((1 + 1/4 + 1/16 + 1/64) * 256)) `
`your rgs/cls layer size / my rgs/cls layer size =  ((your RPN conv's output * 1 * your number of anchor's scale) / (256 * (1 + 1/4 + 1/16 + 1/64) * 1))`

In a word, I think you could try to decrease your RPN conv's output and your number of anchor's scale as well as share base model among FPN and Fast-RCNN.

Anyway, there may be other causes before I saw your source code.

**Comment by leighton613** [comment]
Thanks @xmyqsh ! That's very thoughtful and detailed analysis. I actually use VGG as base for convenience but that doesn't matter at this time. The problem was resolved by changing tf configuration, and let this program to use all the GPU...

Also, I read your updated code, and the one shared `anchor_target_layer` (instead of having four) is helpful to save some RAM of course ;) However, the (possible) downside is, some of the four roi-pooling layers get empty input (no proposals for this scale) and then get `cudaCheckError() failed`. Wonder if anyone encountered this (or I mis-implemented some part)?

**Comment by leighton613** [comment]
@xmyqsh Thanks! I'll take some time into op later... For now I changed `_calc_level` related function to ensure there won't be any empty rois.

**Comment by jiaxiaoharry** [comment]
@xmyqsh Hi, I've been testing your code but got the same issue "cudaCheckError() failed in ROIPoolForward: invalid device function".  Could you show me more details of how to hack the roi_pooling_op_gpu L100 and L205 to cope with it? Thank you.
